### ISSUE TITLE
Mode for "only one slice per column"?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BJumblr#1]
This would make it easier to draw a new configuration without worrying about a) playing two slices at the same time or b) having a column without a slice (i.e. one slice, not more or less).

**Comment by sjaehn** [comment]
Intersting option. But I've no idea how to realize it (at least with a sequencer pattern). If you start with a "legal" diagonal line pattern and you remove, add or move (not implemented yet) a single pad, you will always get an "illegal" pattern (with no or two pads per column). And you can't use cut, copy & paste anymore.

**Comment by sjaehn** [comment]
Just thought about it. In the case you described, you want to move a pad horizontally. One row will be emptied whilst the other row will contain two pads in this case. And therefore a piece of the audio stream (corresponding to the empty row) will be lost. I can add this feature.

... but do you really want it (as it is a limitation of functionality)?

**Comment by mxmilkiib** [comment]
With the "legal" pattern, if I click on any other box in the second column other than the lit up second up box, I would like that lit second up box to disable itself automatically.

**Comment by sjaehn** [comment]
I understood. If you want it for live mixing (you mentioned a possible use with Mixxx at linuxmusicians.com), then it makes sense. I can add a switch. How to call it? "Simple mode", "Single mode", "Live mode", ... ?

Keep in mind that you will loose some interesting functionality in this mode. No background echoes, no canons.

**Comment by mxmilkiib** [comment]
Hmm, good point, maybe then having something half-way like an up-and-down "Max per column" number selector would allow the user to choose? If it were set to say, three, and three boxes were already in a column, clicking a 4th would unselect the 1st selected, and clicking another would then replace the second that was selected?

**Comment by sjaehn** [comment]
I just uploaded a new commit that adds an option to switch between both modes: d9a07ecdfcbaae0e1b21f9f3d583622ae0bfdd85

The ADD mode allows to add (or delete) pads to (or from) a column (like in the old version). The REPLACE mode only allows exactly one pad per step (as you suggested). Programming cut, copy, paste, and flip was more complex than I thought. 

"Max per column" would be too complex. For programming and for the user.
