### ISSUE TITLE
Multiple patterns

### ISSUE THREAD

**Issue by sjaehn** [sjaehn/BJumblr#10]
Requested today by @unfa in his youtube livestream (https://www.youtube.com/watch?v=MmGLTOkNenc):
Store multiple patterns in one instance of B.Jumblr. Add a control port to select the respective pattern. This should enable automation controlled switch between the patterns.

**Comment by sjaehn** [comment]
Feature requested by @unfa is added in c26383d361156792d01a4d3ec42b48c7f14a3465. Still some testing required.

Usage: Add new page/pattern by clicking on the + symbol of the page tab. Press the ▶ symbol in the tab to play the respective page.  This feature can be automated as it is connected to a control port (playback_page). Click on the tab to highlight and to edit the respective page.

Some additional ideas for the future: Increase max. numbers of tabs (requires reduction of data transferred before, tab scrolling), connect tabs to optional MIDI input.

**Comment by sjaehn** [comment]
Now, up to 16 pages/patterns are allowed. Updated in 69f2e44720044648ec4386d9ab388125e8a70e8d.

**Comment by sjaehn** [comment]
MIDI control is enabled in 1ee46d02bb2200ba49c1cbc5bbdd405d83677aec.

Now you can connect a page to a note on or note off or control change (CC) signal. Thus you can switch playback pattern using MIDI. Some examples:
* Switch playback pattern depending on the MIDI note
* Switch playback pattern depending on the velocity
* Switch playback pattern depending on CC message type or value

MIDI learning is enabled too.

**Comment by sjaehn** [comment]
TODO: Fade between patterns (fix nasty clicks)

**Comment by unfa** [comment]
https://youtu.be/4GcZw2j5xGM
I've given this a test-drive today, and I love it, though there's some minor issues.

1. it seems that after changing the current pattern, B.Jumblr looses the beat - I think it should wait until the current slice finishes and continue from the newly selected pattern then. O maybe provide an option to change that behavior, but I guess that'd be best or default.

Right now I think it's switching mid-slice which produces a weird problem with stuff being off-beat fro a moment unless the user flipped the pattern in a short window where it produces musical results.

What do you think?

**Comment by sjaehn** [comment]
Thanks for your information. I've to watch the video a few times more to fully understand what you did and what the plugin did. It's a bit too fast for my ears to fully analyzed all informations. Question: Did you connect it to an external MIDI device to switch between the patterns? Or did you use a MIDI track or an automation curve (I don't see)?

Edit: I just saw you used a version before I added MIDI. Thus you likely automated the playback_page control port.

I guess you noticed the visual differences in the new version compared to that you used in your video stream two weeks ago. And I hope these changes didn't cause confusion. The horizontal white progression line is replaced by a yellow-framed horizontal line. And the new vertical white lines show which slice is actually played. But only for the actually played pattern. Thus, if the pattern you actually working on (highlighted tab) is NOT the actually playing pattern (tab with the black play symbol) you don't see any white line. Natch.

In theory, B.Jumblr itself shouldn't loose the beat. The horizontal progression line continues even if you switch the playback page. This also works if you are half-way in a row. And there is a fader algorithm implemented to softly slide from one page/pattern to the other. But this is only a slide in volume, not in time!

But there are two known ways that the plugin "seem" to loose the beat:

1. User controlled. Let's say all odd columns are on-beat and all even columns are off beat. Than you will switch from off-beat to on-beat (or vice versa) if the pad in the actually playing row is off-beat in the first pattern and on-beat in the other.

2. The fader algorithm mentioned above. There are some unexpected results if the step fader collides with the page fader. Although the faders only influence the volume and not the time aspect, it may sometimes "sound like" being off-beat. In a first quick fix I successfully removed the majority of the nasty clicks which are produced if both sliders overlap. But the fader algorithm still produces unwanted conditions and needs to be rewritten.

**Comment by sjaehn** [comment]
There are some short "flickering" sounds, especially at 1:41, 1:47, and 2:01. This is either due to the fader issue I mentioned above. Or it is the result of page switching just before the end of a progression step (=row) which results in a very short playing of the remainder of the progression step.

I just think about your idea to schedule pattern switch until the next progression step instead of real-time switching. In this case I would hit two birds (fader issue and short remainders) with one stone. And it would reduce programming work as there wouldn't be any need to fully rewrite the fader algorithm anymore (step fade and page fade are synchronous).

**Comment by sjaehn** [comment]
@unfa, waiting for page/pattern change until the next step progression is a really good idea. Implemented in b872b759511c356fb8cb4fc760f41cb5947f19ac.

**Comment by grammoboy2** [comment]
When working with it, you start to think about the option you'll find in non-sequencer. Most notably the phrase editor, where you can play the made patterns in a certain sequence (to make a song / beat). 

http://non.tuxfamily.org/sequencer/doc/MANUAL.html#n:2.2.
