### ISSUE TITLE
Grid could be more clear

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BJumblr#16]
The division of the grid in fours is visible via color differences (blue vs black), but that could be a bit more clear imho. 

Fun project for sure!

**Comment by sjaehn** [comment]
I'll take a look and I will play around with the colors.

**Comment by sjaehn** [comment]
I just made the blues a tiny bit brighter in dab1eb6c1af8f392f7e918187ed382abac148709 . Better?

**Comment by grammoboy2** [comment]
On 11/9/20 9:21 PM, sjaehn wrote:
>
> I just made the blues a tiny bit brighter in dab1eb6 
> <https://github.com/sjaehn/BJumblr/commit/dab1eb6c1af8f392f7e918187ed382abac148709> 
> . Better?
>
That was fast. Yes, much better.
>
