### ISSUE TITLE
save presets?

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BJumblr#17]
Would be nice to be able to save presets, that's only possible via Carla 'save as'?

**Comment by sjaehn** [comment]
Thanks for the question. But this is exactly the way you have to go. In the LV2 standard, it's the task for the *host* to save and restore plugin states (and presets). Therefore all LV2 hosts (Carla, Ardour, Zrythm, ..., and even jalv) *must* provide the option to save and load presets. 

I know, this is a bit different compared to plugins from the vst world.
