### ISSUE TITLE
CPU high

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BJumblr#19]
When running the plugin in Carla 2.2, it gives me a cpu % of 64 in htop (reasonable modern cpu with 4 cores).

**Comment by sjaehn** [comment]
I know this problem from other B.Music problems but not for B.Jumblr, yet. B.Jumblr is not that CPU hungry. With the following three exceptions:
(i) If there are more than on pad set in a row, the respective number of samples are played simultaneously. If 16 pads are set, 16 samples are played. But this shouldn't be the problem. 
(ii) Some more CPU time is required for fading between the pads. But still, this shouldn't be a problem.
(iii) The GUI isn't that hungry but its graphics run on CPU too. As I use Cairo (TODO switch to nano or sth. else). This may become a problem if you set very short step sizes. Here I can put my hands on.

I just tested it on a Skylake i5 U-series CPU with 1/16 beats, 1 tab, and the 16x16 pattern filled by > 50 %: <30% cpu.

**Comment by sjaehn** [comment]
If this problem persists compile with `make CPPFLAGS+=-O3`
