### ISSUE TITLE
In plugin bypass button?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BJumblr#2]
For being able to quickly take the effect in and out of the mix.

**Comment by sjaehn** [comment]
Question: Shouldn't the host be responsible for it?

**Comment by mxmilkiib** [comment]
The host most likely has a bypass option, but for convenience to the user plugins often have their own a bypass. Like [LSP](https://lsp-plug.in/?page=video), or even SliceShuffler, which has both a bypass button and it's own wet/dry knob.

**Comment by sjaehn** [comment]
You will get it. But the dry/wet in SliceShuffler is mainly to get delay effects like echoes, I think. B.Jumblr offers an other way to achieve this goal (more than one pad per step and/or leveling the pad by mouse wheel scrolling).

**Comment by sjaehn** [comment]
Bypass button added in 4df5a19c57587b4b79a25d54798e3566c17b988e . Next to play button.
