### ISSUE TITLE
UI is using fork for opening help link

### ISSUE THREAD

**Issue by falkTX** [sjaehn/BJumblr#27]
fork in unwanted for audio applications.
related https://github.com/sadko4u/lsp-plugins/issues/54

Carla tries to prevents plugins from calling `fork` under certain conditions.
Resulting in not being able to open the links in this plugin.

> Carla prevented a plugin from calling 'fork', bad plugin!
> sh: 1: Cannot fork
> BJumblr.lv2#GUI: Can't open https://www.youtube.com/watch?v=DFSi7TMqvMw. You can try to call it maually.

**Comment by falkTX** [comment]
Just realized there is a typo on that sentence, "maually"

Also seems to be missing the newline.

**Comment by sjaehn** [comment]
Thanks @falkTX. The plugin UI calls system() with "xdg-open" and a URL from the non-RT UI thread. I'll have a closer look to it and I'll think about alternatives.

Typos are fixed in 51dbdc14118594ff35ac31365f3c3bd5d6e46f86. But similar typos may exist in the other B.Music plugins and will be fixed soon.

**Comment by falkTX** [comment]
ah, so it is xdg-open that uses fork to open the native desktop tool hmmm..

using `system` from within the plugin might still be off, not sure.

**Comment by sjaehn** [comment]
Do you have any other / smarter idea to call the system web browser / URL that would work here?

**Comment by sjaehn** [comment]
`system()` is the bad guy as it seems to call `fork()` (see https://pubs.opengroup.org/onlinepubs/9699919799/functions/system.html# ).

**Comment by falkTX** [comment]
I was told by rgareus on #ardour that ardour uses vfork + exec of x-www-browser to open links.

**Comment by sjaehn** [comment]
Thanks, falkTX. I just ended up at the same and I'm now writing my on function doing exactly this. Update will follow soon.

**Comment by sjaehn** [comment]
system() replaced in b6ab490968c5b9a150496975753e27c688884d74. I hope it should work now. @falkTX please let me know. Then I would paste this fix to all the other B.Music plugins.

**Comment by falkTX** [comment]
will try. but please do not use absolute path as in `/usr/bin/x-www-browser`.
that will break guix and maybe others.

**Comment by sjaehn** [comment]
This is only a fallback. The makefile looks for the location of `x-www-browser` via `which $(WWW_BROWSER)`, stores the result in `WWW_BROWSER_CMD` and  send this to `$(CXX)` using the `-D` flag: https://github.com/sjaehn/BJumblr/blob/b6ab490968c5b9a150496975753e27c688884d74/makefile#L38-L40

Thus this should work automatically with any `x-www-browser`-using system. But you are free to build with `make WWW_BROWSER=...` or `make WWW_BROWSER_CMD=...` for systems without any `x-www-browser`.

**Comment by falkTX** [comment]
yes I saw that, but that is exactly what will not work under guix. packages are put into containers, with no access to /usr/bin/
it is best to just call without an absolute path.

why do you need the absolute path?

**Comment by sjaehn** [comment]
`execve()` only runs with the absolute path.

**Comment by falkTX** [comment]
there are many variants of exec, some dont need absolute path

**Comment by sjaehn** [comment]
As far as I understood I've to call an `execv...()` following `vfork()`. And all of them need an absolute path.

**Comment by sjaehn** [comment]
It would be much easier without `execv...()`. I don't know if I can do this.

**Comment by falkTX** [comment]
from the manual of exec:

>    Special semantics for execlp() and execvp()
>       The execlp(), execvp(), and execvpe() functions duplicate the actions of the shell in searching for an executable file if the specified filename does not contain a slash (/) character.  The  file  is
>       sought  in  the colon-separated list of directory pathnames specified in the PATH environment variable.  If this variable isn't defined, the path list defaults to a list that includes the directories
>       returned by confstr(_CS_PATH) (which typically returns the value "/bin:/usr/bin") and possibly also the current working directory; see NOTES for further details.
>       If the specified filename includes a slash character, then PATH is ignored, and the file at the specified pathname is executed.

**Comment by falkTX** [comment]
I think using a relative path is fine here

**Comment by sjaehn** [comment]
I agree, I've overseen the `execvpe()`. I'll try. This would have saved a lot of work if I would have seen it before :-).

**Comment by sjaehn** [comment]
OK, fixed in ff9ab2b7efcbcaaf9d6dab2b0b4a82a15f8fff7d. It works for me with `execvpe()`. Path is detected automatically. `x-www-browser` is still substitutable by `make WWW_BROWSER_CMD=...`.
