### ISSUE TITLE
File selection dialog cant navigate anywhere

### ISSUE THREAD

**Issue by falkTX** [sjaehn/BJumblr#28]
See screenshot below

![Screenshot_20210409_154600](https://user-images.githubusercontent.com/1334853/114197941-c49a2c80-994a-11eb-8b06-953330974776.png)

I have nowhere to click to go up a directory, or home, or root.
I am locked out from selecting any files.

Also note how no folders are visible either..

Using v1.6.4

**Comment by falkTX** [comment]
This might be related https://github.com/brummer10/Fluida.lv2/issues/5
another plugin UI had similar issues on my system.
Might be due to using XFS.

**Comment by sjaehn** [comment]
Hopefully fixed in 81d3f7e3d81fb338e0ac92f50bd87276e2cad189

**Comment by falkTX** [comment]
Can confirm, now I am able to load some files.
Thanks
