### ISSUE TITLE
Instead of hardcoding the web browser executable it is better to use xdg-open

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BJumblr#30]
You maintain the ```WWW_BROWSER_CMD```, see here: https://github.com/sjaehn/BJumblr/blob/master/src/BJumblrGUI.hpp#L75

It is much easier to just launch ```xdg-open https://www.site.com``` in order to open it in the currently default browser.

**Comment by sjaehn** [comment]
There were issues about `xdg-open` as well. Therefore I decided to use `x-www-browser` by default (see https://github.com/sjaehn/BJumblr/blob/cea8e2b11c670d0c5d4f783ced56de4ddcc5eeb0/src/BJumblrGUI.hpp#L74-L76). It should exist on all X systems. But feel free to compile with `make WWW_BROWSER_CMD=xdg-open`.

**Comment by yurivict** [comment]
This works, thanks!
