### ISSUE TITLE
3 and 6, and 1/3, 1/6, etc. for patterns and steps?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BJumblr#4]
To accommodate other common rhythms and time signatures.

**Comment by sjaehn** [comment]
Good idea. Do you think about a waltz ;-). 

Two ways to implement:

a) Simply add 3, 6, 9, 15, 18, and 30 to nr_of_steps popup menu; and 3, 1/3, 1/6, 1/12 to stepsize popup menu. No more changes required.

b) A more intelligent solution would be to transfer the beats_per_bar information from DSP to GUI and to display either base 3 or base 4 nr_of_steps and stepsize popup menus depending on the beats_per_bar information. This would be a bit more work.

Anyway, do you really need it? As you can choose between beats and bars as base, you are always able to make 1/16, 1/8, 1/4, 1/2, 1/1 note steps. Even in less common time signature like in Bach's prelude in C BMV 547 (9/8) or Metallica's Nothing else matters (partial 12/8).

**Comment by mxmilkiib** [comment]
[Dub delays](https://youtu.be/axzjOUsOckk) and [psytrance triplets](https://www.youtube.com/watch?v=dZ0HyU-yecc&list=PLs7515sqXL3g2qzMvf71E2FOtlbS0xcaM&index=2) were my thoughts :)

17/8 for Noisia's [The Hole Pt. 1](https://www.youtube.com/watch?v=y5E7W9minGw) ;)

It's not an immediate need, but I think that a polyrhythmic play between rhythm timings, even just 4/3, is such a powerful tool for making things sound interesting.

**Comment by sjaehn** [comment]
beat_unit = 3, this is odd. Therefore I will implement it. Method a, method b wouldn't make sense as we are talking about the denominator.

**Comment by sjaehn** [comment]
Feature added in 76c8de4debbd5fe881ab18fdc29a1fee45446754 . If need even more exotic steps (like 1/7), you can manually set them in the generic GUI provided by the most LV2 hosts.
