### ISSUE TITLE
Control inputs for manual triggering of sample advance+playback / repeat playback?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BJumblr#5]
Allowing playback to be controlled manually by having two control inputs, one that on a 1 input triggers the advance of the white line and the playback of the sample in the new column, and another that triggers repeats the playback of the same sample.

Whilst I'm mentioning a trigger mechanism, it might be worth my suggesting that the use of [CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701) rather than control could allow for trigger, gate, and modulation of the amplitude of the signal, though that would be a whole other level!

**Comment by sjaehn** [comment]
Interesting idea. I've no experience with CVport, yet. Another trigger mechanism would be the MIDI gate (also used in B.Shapr).

**Comment by sjaehn** [comment]
Hi Milk,

I thought about it. I'm not 100% sure if I understand you in the right way. 

a) Do you think only about input triggers which can "press" the "<" and the ">" button ? This would cause the (floating point value) step position by -1.0 (step_position = step_position - 1.0),  or +1.0  (step_position = step_position + 1.0), respectively. As you know. 

b) Or do you think about triggerable buttons to jump to the start of the current (step_position = floor (step_position)) or the start of the next step (step_position = floor (step_position + 1.0)), respectively?

c) Or do you think about a (CV port-controlled) fine tuning of the position (like step_position = step_position - 0.01 or step_position = step_position + 0.01) ?

**Comment by mxmilkiib** [comment]
I was meaning d) as in the sample playback isn't triggered by the transport, but by a trigger signal coming in as either an LV2 port property trigger or an LV2 CV trigger.

So one could, with an irregular clock coming from another plugin, play the slices of the sample loop at that irregular rhythm.

Saying that, having seen at this [Modular Monthly: Creative sampling with the Ginko Synthese Sampleslicer](https://www.youtube.com/watch?v=tB3e7AFfKyY) video, I think there's probably more general expressive possibility in being able to "sample and hold" the current loop (rather than advance the loop that is used from further input signal), and also be able to control the length and start position of the part of the loop that is being played (a loop within a loop, if you will :)

**Comment by sjaehn** [comment]
I'm thinking about how to realize it. There is not only one tough nut to crack. The input would be the easiest part.

**Comment by sjaehn** [comment]
The nut is cracked in e1b2f3e0cab58cf52814c6c7445b3c1fb90ad3e1. It took a wile as I experimented with LV2 patch and param features (and ended up with classic controls again). And please keep in mind that B.Jumblr isn't a sample slicer. It is a delay.

The solution: Two additional controls. 

The manual progression delay control port (controlled by the new white buttons) enables a manual movement of the white line upwards or downwards. This movement is managed by the introduction of an additional delay value : the manual progression delay. Pressing the up button results in a jump of a whole step up (increase delay by 1.0 steps). Pressing the down button results in a jump of a whole step down (decrease delay by 1.0 steps). If you press one of these buttons in the middle of one step, you will end up in the middle of the next step (or previous step, respectively). It is also possible to change the buttons behavior to jump to the start or the end of the respective step. I think this would be what you suggested. And it is possible to program to connect these buttons to a CV port. But then you have to define trigger values (= additional control ports)... Do you still need them if you can control (and automate) the progression via the manual progression delay control port ?

There is also a new white home button that simply sets the manual progression delay value to zero.

The second new control is the speed control. The rationale of this control is to update the progression delay at the end of each step. Speed == 1.0 : normal playback. Speed == 0.0 : no progression, endless loop, delay is increased by one step at the end on the step. Speed == 0.25 : playing 4x the step then progression....  At present, this control can stepwisely be changed by  0.25. This limitation can be removed, if you want.

And there is a display that shows the sum of the two delays.

These changes enable the key features seen in the very interesting Ginko Synthese Sampleslicer video.

PS: Please notice the change in direction as mentioned [here](https://github.com/sjaehn/BJumblr/issues/7).

**Comment by mxmilkiib** [comment]
I've just found some time to test this, it's wonderful, thanks once again :)
